### ISSUE TITLE
go get failing

### ISSUE THREAD

**Issue by gcstang** [kothar/go-backblaze#21]
go get -u gopkg.in/kothar/go-backblaze.v0/b2

`# cd .; git clone https://gopkg.in/kothar/go-backblaze.v0 /Users/myuser/tclg/GitRepositories/personal/GoLang/src/gopkg.in/kothar/go-backblaze.v0
Cloning into '/Users/myuser/tclg/GitRepositories/personal/GoLang/src/gopkg.in/kothar/go-backblaze.v0'...
fatal: unable to access 'https://gopkg.in/kothar/go-backblaze.v0/': Unknown SSL protocol error in connection to gopkg.in:-9838
package gopkg.in/kothar/go-backblaze.v0/b2: exit status 128`

**Comment by gcstang** [comment]
Local required this setting in order to retrieve:
`git config --global http.sslVerify true`

**Comment by prologic** [comment]
Please reopen and keep this open until this is resolved upstream

**Comment by prologic** [comment]
The solution here is a work-around and breaks security

**Comment by gcstang** [comment]
@prologic this has nothing to do with this project and only git and only gopkg.in specifically.

**Comment by prologic** [comment]
Doesn't matter. Keep the issue open for visbility.
Closing it when the issue still exists upstream is premature.

Clearly mark it with an appropriate label and edit the original description
to be clear so others can easily discover the issue.

It would be good to also notify the upstream maintainers of gopkg and/or
the affected package itself too.

cheers
James


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au
