### ISSUE TITLE
Each upload is requesting a new b2_get_upload_url.

### ISSUE THREAD

**Issue by antihax** [kothar/go-backblaze#22]
It appears that each upload is requesting a new b2_get_upload_url and while I am attempting to concurrently upload a few million files, the progress is very slow.

Unless I am mistaken, the URL should be reused and they should be pooled. If an upload fails, the URL should be discarded from the pool. If they are all in use, a new one should be requested.

https://www.backblaze.com/b2/docs/b2_get_upload_url.html

**Comment by antihax** [comment]
I planned to take a look tonight. I may open a PR to track and keep it in
WIP until it is finished.

**Comment by antihax** [comment]
Had #23 in production overnight, significant drop in get upload URL requests.

**Comment by kothar** [comment]
Closing, patch very much appreciated 😄
