### ISSUE TITLE
"Uncrecognised bucket type: snapshot" on all bucket operations

### ISSUE THREAD

**Issue by encryptio** [kothar/go-backblaze#5]
I'm getting the error "Uncrecognised bucket type: snapshot" (lit.) for all bucket operations after I experimented with the snapshot functionality recently added to B2.

NB: This error occurs while trying to open a bucket not related to the snapshot bucket at all.

This is likely from the [https://www.backblaze.com/b2/docs/b2_list_buckets.html](new `"bucketType": "snapshot"`) returned for the snapshot buckets.

**Comment by kothar** [comment]
Sorry this was slow to fix - should be working now.
