### ISSUE TITLE
Multiple parallel uploads are failing

### ISSUE THREAD

**Issue by ErhanAbi** [kothar/go-backblaze#9]
I receive the following error when trying to upload files concurrently.

`bad_request: more than one upload using auth token <redacted upload token>`

This is due to the fact that the same upload url is used underneath which is fetched on bucket.internalGetUploadURL() and stored as a property on the bucket itself. Thus, this limits the bucket on using the `UploadFile()` once at a time.

I think the `easy` fix in this case would be to not store the `auth property` anymore on the bucket, and fetch the uploadURL everytime when uploading a file or when calling `GetUploadURL` method (which also the correct use-case, there's no need for storing the uploadURL ahead of time - bc it can expire).

**Comment by kothar** [comment]
Ah, yes, I forgot that B2 have stopped parallel uploads using the same token (this did work during the beta). Thanks for this and the other PR, I will look at both this afternoon!

**Comment by kothar** [comment]
@pfzero - This is working with the tool in /b2, parallel uploads complete as expected.

Regarding storing the upload URL, I have switched to using a pool to store recent upload URLs. It may be that some expire, but this should be treated as a non-fatal error by any code using the library (it will need to handle other non-fatal errors such as server errors, so this should not add any overhead)
